name: encrypted_text_proj
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.10
  - pip
  - pip:
      - numpy==1.19.5
      - pandas==1.2.4
      - tensorflow==2.5.0
      - matplotlib==3.4.2
      - seaborn==0.11.1
      - pytest==6.2.4
      - scikit-learn==0.24.2
      - wandb==0.10.30
